define({
    'country': 'Pays',
    'fromyear': "D'Annee",
    'toyear': "A l'Annee",
    'world': 'Monde',
    'continents': 'Continents',
    'regions': 'Régions',
    'agriculture_total': 'Agriculture Total',
    'countries': 'Pays',
    'sector': 'Secteur',
    'show_hide_table_breakdown': 'Afficher/Masquer la table Ventilation',
    'country_region': 'Pays/Régions',
    'enteric_fermentation': 'Fermentation entérique',
    'sum_of_countries': 'Somme des Pays',
    'manure_management': 'Gestion du fumier',
    'agricultural_soils': 'Culture de sols organiques',
    'rice_cultivation': 'Riziculture',
    'burning_crops_residues': 'Combustion - résidus de récoltes',
    'burning_savanna': 'Combustion - Savane',
    'ghg_overview_title': 'Aperçu régional des émissions',
    'ghg_overview_note': "Sélectionnez un (des) pays et d’autres détails ci-dessus. <br> L'outil fournira une série de résultats au format graphique et tabulaire. <br> Lors de la sélection de deux ou plusieurs pays, l'information sera présentée comme une somme.",
    'ghg_overview_subnote': "Pour plus d'informations, un guide de l'utilisateur est disponible ici.",
    'agriculture': 'Agriculture',
    'land_use': 'Utilization des terres',
    'category': 'Catégorie',
    'no_data_to_display': 'No data to display',
    'grand_total':'Total',
    'select_one_or_more_countries': 'Sélectionnez un ou plusieurs pays',
    'continent': 'Continent',
    'region': 'Région',
    'total': 'Total',
    'pie_mu': 'Gg CO2eq',
    'user_instructions': 'User Instructions',
    'export': 'Exporter',
    'avg': 'Moyenne',

    'by_world': 'Agriculture Total par continent (Gg CO<sub>2</sub>eq)',
    'by_continent': 'Emissions par catégorie agricole et par continent (Gg CO<sub>2</sub>eq)',
    'by_region': 'Emissions par catégorie agricole et par région (Gg CO<sub>2</sub>eq)',
    'by_country': 'Emissions par catégorie agricole et par pays (Gg CO<sub>2</sub>eq)',

    'charts': 'Graphiques',
    'tables': 'Tableaux',

    contextButtonTitle: "Imprimez/Exportez graphique",
    downloadJPEG: "Imprimez graphique, Téléchargez image PNG/JPEG",
    downloadPDF: "Téléchargez document PDF",
    downloadPNG: "Téléchargez PNG",
    downloadSVG: "Téléchargez image vectorielle SVG",
    printChart: "Imprimez/Exportez graphique",
    resetZoom: "Réinit. zoom",
    resetZoomTitle: "Réinitialiser zoom 1:1"
});